### ISSUE TITLE
Sensors are not listed alphabetically

### ISSUE THREAD

**Issue by nleo575** [tetujin/aware-client-ios-v2#15]
This is a feature request to list all of the sensors alphabetically instead of in a random order. The current ordering makes the app more difficult to use. Having all of the sensors listed alphabetically would make it easier to use when you need to change a sensor setting.

**Comment by tetujin** [comment]
Hi @nleo575 , Thank you for your suggestion. I added the sort function to the client! 

[ViewController.swift](https://github.com/tetujin/aware-client-ios-v2/commit/02caf3cf76407bdb71f3bc83a087c864afd72d3b) #2 fixed
