### ISSUE TITLE
Activity Recognition default value is inconsistent

### ISSUE THREAD

**Issue by nleo575** [tetujin/aware-client-ios-v2#16]
For the Activity Recognition sensor, the default value on the dashboard and in Android is 60 seconds. The default value in the iOS app appears to be 300 seconds. This value should be changed to 60 seconds for consistency.

Severity Rating: 2 out of 4 - Minor

**Comment by tetujin** [comment]
@nleo575 Thank you for the report. The value is managed in the AWARE library.
I modified the setting in the library. You can check it on this [link](https://github.com/tetujin/AWAREFramework-iOS/blob/ba2112bfd7de9e64f09e5977990d7adc3b7a2321/AWAREFramework/Classes/Plugins/IOSActivityRecognition/IOSActivityRecognition.m#L84).
