### ISSUE TITLE
Missing SignificantMotion?

### ISSUE THREAD

**Issue by bl166** [tetujin/aware-client-ios-v2#2]
aware-client-ios-v2-master/Pods/AWAREFramework/AWAREFramework/Classes/Sensors/SignificantMotion/EntitySignificantMotion+CoreDataProperties.h: No such file or directory

**Comment by tetujin** [comment]
Hi @bl166 

I'm sorry for my late reply. Can you try to remove `Podfile.lock`, and try to use  `pod install` command on your terminal? 

I think you need to update the CocoaPods libraries before building the app. The sensor of `Significant Motion` is a new function of the AWAREFramework library, so then you need to update the library yourself by using the command above.

Best,
Yuuki
