### ISSUE TITLE
Device ID copy/share function in order to link key ID with other system easily

### ISSUE THREAD

**Issue by gps1111** [tetujin/aware-client-ios-v2#20]
Confirming Device ID is available on the setting view.
However, current iOS client doesn't have the function to share or copy/share the Device ID. So that if other system would like to use AWARE Device ID to share the data, user need to type Device ID manually. This is not user friendly because Device ID is so long.

**Comment by tetujin** [comment]
This function is implemented on the [latest commit](https://github.com/tetujin/aware-client-ios-v2/commit/496fce2b23cec1963fb53e07d6c9ab159b48ef1b). Thank you for proposing a nice idea!
